### ISSUE TITLE
After updating to 1.1 getting this: NoMethodError (undefined method `info' for nil:NilClass): 

### ISSUE THREAD

**Issue by asavin** [omniauth/omniauth#597]
Here is a log:

Started GET "/users/auth/facebook" for 127.0.0.1 at 2012-04-13 12:06:10 +0300

NoMethodError (undefined method `info' for nil:NilClass):
  omniauth (1.1.0) lib/omniauth/strategy.rb:151:in`log'
  omniauth (1.1.0) lib/omniauth/strategy.rb:190:in `request_call'
  omniauth (1.1.0) lib/omniauth/strategy.rb:174:in`call!'
  omniauth (1.1.0) lib/omniauth/strategy.rb:157:in `call'
  omniauth (1.1.0) lib/omniauth/builder.rb:48:in`call'
  warden (1.1.1) lib/warden/manager.rb:35:in `block in call'
  warden (1.1.1) lib/warden/manager.rb:34:in`catch'
  warden (1.1.1) lib/warden/manager.rb:34:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
  rack (1.4.1) lib/rack/etag.rb:23:in `call'
  rack (1.4.1) lib/rack/conditionalget.rb:25:in`call'
  actionpack (3.2.2) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
...

Was working nicely before gem update.
