### PR TITLE
Better handle errors that come from the actual app.

### LINKED ISSUE #1030: Rescue StandardError makes all development errors failures
Since bumping omniauth from 1.9.1 to 2.0.1 in [our application](https://github.com/ualbertalib/jupiter) all development errors have become failures.  For example I purposefully introduce an error to a view.  It is caught by omniauth and calls fail which means that we can no longer use [better_errors](https://rubygems.org/gems/better_errors) to debug.  

```
195:       rescue StandardError => e
    196:        binding.pry
 => 197:         return fail!(e.message, e)
    198:       end
    199: 
    200:       @app.call(env)
    201:     end

[1] pry(#<OmniAuth::Strategies::SAML>)> e
=> #<ActionView::Template::Error: undefined local variable or method `oops' for #<#<Class:0x00007f533c178068>:0x000055e0bcf640a8>>
```

Is there something that we misconfigured in omniauth setup?  We catch the failures to give users a message in their browser
https://github.com/ualbertalib/jupiter/blob/fe8409b9d4b4345e409c91a0cf6744b9ce4b91ba/config/initializers/omniauth.rb#L22
We can make this conditional based on environment but wondering if there is a better way?

https://github.com/omniauth/omniauth/blob/40e354c71094b663f928e1a987977690b67f2aa4/lib/omniauth/strategy.rb#L190-L197

### PR DESCRIPTION
**Pull request by BobbyMcWho**
As a consequence of the changes that were merged in #689, errors
thrown by strategies that utilize other_phase (or more specifically
call_app!), would be caught by omniauth, causing headaches for folks
looking to have those errors handled by their application. This
should allow for errors that come from the app to pass through, while
passing errors that come from the authentication phases to the fail!
handler.

Resolves #1030

### CODE REVIEW

**Review by stnert — APPROVED** [review]

File: lib/omniauth/strategy.rb [hunk 1]
```diff
@@ -462,6 +466,9 @@ def query_string
 
     def call_app!(env = @env)
       @app.call(env)
+    rescue StandardError => e
```
Comment (pgwillia) [inline lib/omniauth/strategy.rb:469]: I was wondering if it would be possible to rescue a subclass of `StandardError` like `OmniAuthError` or something like that.  I guess the challenge is that `call_app` is called from the other dependent gems (omniauth-saml, etc) and you can't really know what will be raised.

**Review by pgwillia — APPROVED** [review]
This works for me.  I can't think of a situation where the environment variable solution shouldn't work.  The tests illustrate the exact situation that we experienced. Thanks @BobbyMcWho
