### ISSUE TITLE
env["omniauth.auth"] return nil

### ISSUE THREAD

**Issue by SandipBhowmick** [omniauth/omniauth#921]
- Provider Gem: 'omniauth', '~> 1.2.1'
- Ruby Version: `ruby 2.2.1p85`
- Platform: `Ubuntu 14.04 LTS`
I want to create different login flow for admin, so I have create another sessions controller under admin. But when I try to access env["omniauth.auth"] from admin/sessions_controller.rb it shows error "NoMethodError at /admin/auth/identity/callback 
undefined method `[]' for nil:NilClass"   I found env["omniauth.auth"] return nil
Please help me

**Comment by thomasedwards** [comment]
Could you post the contents of your `sessions_controller.rb`?

**Comment by SandipBhowmick** [comment]
https://gist.github.com/SandipBhowmick/ac48f62be008a144ea0dc06b677ad4a4

**Comment by thomasedwards** [comment]
I think it’s because the `env[]` is part of the request, try using:

```
request.env["omniauth.auth"]
```

instead.

**Comment by SandipBhowmick** [comment]
request.env["omniauth.auth"] it is also nill

**Comment by thomasedwards** [comment]
Does `auth_hash` need to be `:auth_hash` on this line?

```
@member = Member.from_auth(auth_hash)
```

**Comment by SandipBhowmick** [comment]
there is method at line no 83

**Comment by coding-bunny** [comment]
I'm running into this problem as well with `request.env['omniauth.auth']` being nil in development and our staging systems.
This worked fine on Rails 6.0 and before, but with Rails 6.1 this suddenly stopped working.

**Comment by BobbyMcWho** [comment]
@coding-bunny did you happen to upgrade to omniauth 2.0 at the same time as rails 6.1?

**Comment by coding-bunny** [comment]
No we were on omniauth 2.0 prior to that.
I actually got it working by adding the following in our initializer:

```
# With the changes in Rails 6.1, as well as the new behavior that's introduced in both omniauth 2.x,
# as well as the Google OAuth implementation, we need to explicitly allow the GET requests as valid method.
# This is currently considered a security violation (CVE-2015-9284) which requires you to handle the incoming
# requests over POST. However this is quite the refactor step to do this during the Rails 6.1 upgrade.
OmniAuth.config.allowed_request_methods = %i[get]
```

Not sure why this worked prior, but that fixed it for now.
Next step is doing the POST implementation properly I suppose.

**Comment by BobbyMcWho** [comment]
Make sure to follow the upgrading to 2.0 guide in the wiki, it should be fairly straightforward to upgrade the bits in your Rails controllers/views

**Comment by BobbyMcWho** [comment]
Also watch your logs because you're going to want to disable the get warning that OmniAuth is going to warn on every auth request

**Comment by coding-bunny** [comment]
I’m keeping the warning so it gets annoying enough for the teams so they will update it xD
