### ISSUE TITLE
Upgrade to 1.0: Undefined method `user_omniauth_authorize_path'

### ISSUE THREAD

**Issue by asavin** [omniauth/omniauth#579]
After upgrading omniauth gem to 1.0 and adding omniauth-facebook gem I started to get this error:

ActionView::Template::Error (undefined method `user_omniauth_authorize_path' for #<#Class:0x00000004c7b510:0x00000004c6daa0>):

This user_omniauth_authorize_path is used for the facebook login button on the page. I wonder what might be wrong and how this should be fixed?

My User model is omniauthable.

class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable
